# MySQL.  Versions 5.0+ are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#

db_config: &db_config
  <% if ENV["DATABASE_URL"].present? %>
  <% uri = URI.parse(ENV["DATABASE_URL"]) if ENV["DATABASE_URL"].present? %>
  username: <%= uri.user %>
  password: <%= uri.password %>
  host:     <%= uri.host %>
  <% else %>
  username: root
  password: ''
  host: localhost
  <% end %>
  adapter: mysql2
  pool: 10
  timeout: 5000
  port: 3306

staging:
  <<: *db_config
  database: coltonmalone_staging
    
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: ''
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: coltonmalone_development

test:
  <<: *default
  database: coltonmalone_test

production:
  <<: *default
  database: pacific-retreat-8615

# production:
  # <<: *default
  # database: coltonmalone_production
  # username: coltonmalone
  # password: <%= ENV['COLTONMALONE_DATABASE_PASSWORD'] %>



