db_config: &db_config
  <% if ENV["DATABASE_URL"].present? %>
  <% uri = URI.parse(ENV["DATABASE_URL"]) if ENV["DATABASE_URL"].present? %>
  username: <%= uri.user %>
  password: <%= uri.password %>
  host:     <%= uri.host %>
  <% else %>
  username: root
  password: ''
  host: localhost
  <% end %>
  adapter: postgresql
  pool: 10
  timeout: 5000
  port: 3306

staging:
  <<: *db_config
  database: coltonmalone_staging

default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: root
  password: ''

development:
  <<: *default
  database: coltonmalone_development

test:
  <<: *default
  database: coltonmalone_test

production:
  <<: *default
  database: pacific-retreat-8615

# production:
  # <<: *default
  # database: coltonmalone_production
  # username: coltonmalone
  # password: <%= ENV['COLTONMALONE_DATABASE_PASSWORD'] %>
