login: &login
  <% username, password, ip = ENV["RAILS_DB"].split(":") if ENV["RAILS_DB"] %>
  username: <%= username || "root" %>
  password: <%= password || "" %>
  host:     <%= ip || "localhost" %>

development:
  adapter: mysql2
  database: coltonmalone_development
  <<: *login
  pool: 5

test:
  adapter: mysql2
  database: coltonmalone_test
  <<: *login
  pool: 1

production:
  adapter:  mysql2
  <<: *login
  database: coltonmalone_production
  pool:     5
